#ifndef ARDUINO_TOOLS_ARDUINO_LOCATIONS_H
#define ARDUINO_TOOLS_ARDUINO_LOCATIONS_H

// Generated by CMake

#define ARDUINO_CLI ("/home/henklaak/Projects/LaakSoftLibraries/ArduinoTools/build/Desktop_Qt_6_7_1-Debug/_deps/arduino_cli-src/arduino-cli")


#endif
